### PR TITLE
Add compression to localStorage

### PR DESCRIPTION
**Pull request by VioletVolatile**
This adds compression for save data in localStorage (reducing the storage usage by about ~80%). I also fixed the localStorage size calculations and added units in the GUI.

I did a lot of testing to make sure we don't corrupt any saves, but I would really appreciate if you reviewed this pull request closely just to be sure.

The LZ-String library should have support all the way back to IE6 so that shouldn't be a problem.

### CODE REVIEW

**Comment by aldergames** [comment]
I found an issue that I fixed. Refer to http://pieroxy.net/blog/pages/lz-string/guide.html
Apparently, we can't use the regular compress/decompress in localStorage on Firefox. The decompress method would return null, making it impossible to load.

**Comment by VioletVolatile** [comment]
Ouch, yeah I missed that one. Odd I didn't run in to any issues though, since my main browser is Firefox.

**Comment by aldergames** [comment]
Might be old FF version on my end? I'm on 44.0.2. I ran across this as soon as I tried to load the new save at least, but with the new compress/decompress functions, it seems to work fine.

**Comment by VioletVolatile** [comment]
I'm on the Firefox 46 Developer Edition, so it might be that they've changed something there, or I was VERY lucky and the compression just didn't pick one of the invalid characters while I was testing.

btw do we have any people testing the game before publishing a new version? Might be nice to have an unstable release channel or something.

**Comment by aldergames** [comment]
Not on a mass scale. A few of the authors/editors help me out from time to time on this.

**Pull request merged**
